seed: 1
sampling:
  initBudget: 60
  maxbud: 75
  mc_iters: 10
  num_inactive: 100
log:
  interval: 4
testfunc: 'langermann6d8m4h'
configs:
  perm: 8
  smp: 2
parallel: False
jobs: 60
agents: 8
horizon: 4
dim: 6
