seed: 1
sampling:
  initBudget: 60
  maxbud: 90
  mc_iters: 4
  num_inactive: 100
log:
  interval: 4
testfunc: 'langermann2dcfg'
configs:
  perm: 6
  smp: 2
parallel: False
jobs: 60
agents: 4
horizon: 4

